### ISSUE TITLE
Labels are cut off in Windows when at 200% scale on HiDPI.

### ISSUE THREAD

**Issue by RocusHalbasch** [cypher256/eclipse-encoding-plugin#10]
Labels are cut off in Windows when at 200% scale on HiDPI. 

![shot](https://user-images.githubusercontent.com/1832119/35699663-b9dbfa34-075e-11e8-8ca9-3656419a396a.png)

**Comment by cypher256** [comment]
Please vote for the Eclipse bug.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471313
I fixed this problem by Comment 12 workaround, but a problem also occurred in Comment 18.

**Comment by RocusHalbasch** [comment]
I did so.
