### ISSUE TITLE
The 4K display is incomplete

### ISSUE THREAD

**Issue by lyh061619** [cypher256/eclipse-encoding-plugin#11]
Autodetect encoding is not fully displayed on the 4K (3840 x2160) screen, and the whole display is hidden a little lower. I hope to adjust it. Thank you

**Comment by cypher256** [comment]
Please vote for the Eclipse bug.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471313
I fixed this problem by Comment 12 workaround, but a problem also occurred in Comment 18.

#10 Labels are cut off in Windows when at 200% scale on HiDPI.
