### ISSUE TITLE
move update site to github pages

### ISSUE THREAD

**Issue by bjmi** [cypher256/eclipse-encoding-plugin#2]
If an update site is provided via raw.githubusercontent.com....
a warning appears in Eclipse Error log.

Server returned lastModified <= 0 for https://raw.githubusercontent.com/cypher256/eclipse-encoding-plugin/master/eclipse.encoding.plugin.update/content.jar

Therefore move your update site to https://cypher256.github.io/eclipse-encoding-plugin (https://pages.github.com/)

**Comment by paulvi** [comment]
Not really an issue for tiny plugin as this.

**Comment by cypher256** [comment]
Created gh-pages update site and updated marketplace url settings.
https://cypher256.github.io/eclipse-encoding-plugin/
Thanks.

**Comment by bjmi** [comment]
No, thank you.
