### ISSUE TITLE
UTF-8 encoding don't show BOM

### ISSUE THREAD

**Issue by itinside** [cypher256/eclipse-encoding-plugin#6]
If you have different UTF-8 encoding files with and without BOM the plugin open it correctly but it would not show in the status bar (is it a file with or without BOM) and you can´t add or remove this.

**Comment by cypher256** [comment]
What is it extension of the file?
Add it extension (ex: *.csv) to the "Text" in the content type preferences.
If it is not in the preferences.

Preferences > General > Content Types > Text > File associations > add

**Comment by itinside** [comment]
I use *.txt files and the following files would not correctly identified.
I have checked with an without Autodetected Set: Automaticly.
Only the second one is correct, but if I remove the BOM I can't add it again.
 
[test_UTF-8_BOM_DOS.txt](https://github.com/cypher256/eclipse-encoding-plugin/files/647487/test_UTF-8_BOM_DOS.txt)
[test_UTF-8_BOM_UNIX.txt](https://github.com/cypher256/eclipse-encoding-plugin/files/647488/test_UTF-8_BOM_UNIX.txt)
[test_UTF-8_noBOM_DOS.txt](https://github.com/cypher256/eclipse-encoding-plugin/files/647489/test_UTF-8_noBOM_DOS.txt)
[test_UTF-8_noBOM_UNIX.txt](https://github.com/cypher256/eclipse-encoding-plugin/files/647490/test_UTF-8_noBOM_UNIX.txt)

**Comment by cypher256** [comment]
Thanks for the example file.
When the number of characters is small,
the juniversalchardet can not detect the encoding.

**Comment by cypher256** [comment]
The detection of BOM depends on the  Eclipse feature.
Open the File Properties and check it.
In the future, this plugin may detect BOM.
