### ISSUE TITLE
Does not correctly detect latin-1 (when default encoding is utf-8)

### ISSUE THREAD

**Issue by tomtom** [cypher256/eclipse-encoding-plugin#7]
It's probably because of juniversalchardet, but this plugin doen't correctly distinguish between utf-8 and latin-1, which led to the corruption of several files. I get no warning or whatever. The original File Encoding Info, which uses ICU, works more reliably in this context and correctly displays a warning.

Maybe you could revise the use of juniversalchardet or support multiple detection libraries?

**Comment by cypher256** [comment]
In version 1.8.4, 
the switching feature between juniversalchardet and ICU4J has been added, 
so it will be closed.
